Changed base of Dockerfile to cgpBigWig
cancerit/dockstore-cgpbigwig pull request #6
Opened 2019-09-30 15:56 UTC by rulixxx

Got all the CWL tests to work with the new base for the container

2019-09-30 16:10 UTC, rulixxx commented
This should close #5

2019-10-01 08:03 UTC, keiranmraine commented on Dockerfile
> -LABEL maintainer="drj@sanger.ac.uk"\
The label section is still required

2019-10-01 08:04 UTC, keiranmraine requested changes
Need the label section still as it is different to the base image in that this is specifically in use for dockstore.org linking of cwl to image

2019-10-01 10:55 UTC, keiranmraine approved these changes

2019-10-01 12:09 UTC, merged